### ISSUE TITLE
快速入门编译报错

### ISSUE THREAD

**Issue by jackqqxu** [DTStack/molecule-examples#2]
按照你们的快速入门，https://dtstack.github.io/molecule/zh-CN/docs/quick-start

发现如下问题，是版本问题？：

Compiled with problems:X

ERROR in ./node_modules/@dtinsight/molecule/esm/components/tabs/dragAndDrop.js 5:19-35

export 'createDndContext' (imported as 'createDndContext') was not found in 'react-dnd' (module has no exports)

ERROR in ./node_modules/@dtinsight/molecule/esm/components/tabs/dragAndDrop.js 12:29-40

export 'DndProvider' (imported as 'DndProvider') was not found in 'react-dnd' (module has no exports)

ERROR in ./node_modules/@dtinsight/molecule/esm/components/tabs/tab.js 50:19-26

export 'useDrag' (imported as 'useDrag') was not found in 'react-dnd' (module has no exports)

ERROR in ./node_modules/@dtinsight/molecule/esm/components/tabs/tab.js 59:19-26

export 'useDrop' (imported as 'useDrop') was not found in 'react-dnd' (module has no exports)

ERROR in ./node_modules/react-dnd-html5-backend/dist/esm/index.js 1:0-42

Module not found: Error: Can't resolve './HTML5Backend' in '/Users/jackqqxu/code/webide/molecule-demo/node_modules/react-dnd-html5-backend/dist/esm'
Did you mean 'HTML5Backend.js'?
BREAKING CHANGE: The request './HTML5Backend' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/react-dnd-html5-backend/dist/esm/index.js 2:0-45

Module not found: Error: Can't resolve './NativeTypes' in '/Users/jackqqxu/code/webide/molecule-demo/node_modules/react-dnd-html5-backend/dist/esm'
Did you mean 'NativeTypes.js'?
BREAKING CHANGE: The request './NativeTypes' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/react-dnd-html5-backend/dist/esm/index.js 3:0-48

Module not found: Error: Can't resolve './getEmptyImage' in '/Users/jackqqxu/code/webide/molecule-demo/node_modules/react-dnd-html5-backend/dist/esm'
Did you mean 'getEmptyImage.js'?
BREAKING CHANGE: The request './getEmptyImage' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/react-dnd/dist/esm/index.js 1:0-25

Module not found: Error: Can't resolve './common' in '/Users/jackqqxu/code/webide/molecule-demo/node_modules/react-dnd/dist/esm'
Did you mean 'index.js'?
BREAKING CHANGE: The request './common' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/react-dnd/dist/esm/index.js 2:0-24

Module not found: Error: Can't resolve './hooks' in '/Users/jackqqxu/code/webide/molecule-demo/node_modules/react-dnd/dist/esm'
Did you mean 'index.js'?
BREAKING CHANGE: The request './hooks' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/react-dnd/dist/esm/index.js 3:0-29

Module not found: Error: Can't resolve './decorators' in '/Users/jackqqxu/code/webide/molecule-demo/node_modules/react-dnd/dist/esm'
Did you mean 'index.js'?
BREAKING CHANGE: The request './decorators' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

欢迎和我微信联系：jackqqxu

**Comment by wewoor** [comment]
@jackqqxu 请参考这个 issue: https://github.com/DTStack/molecule/issues/570

欢迎来我们 Discord 在线交流：https://discord.com/invite/b62gpHwNA7
