### ISSUE TITLE
中英文显示问题

### ISSUE THREAD

**Issue by BojunZhong** [DTStack/molecule-examples#4]
![5e6c167b0fde777b126401993040ab4](https://user-images.githubusercontent.com/102637083/171084165-080e60e6-5236-47d5-bb12-51fa3a022706.png)
![74de87eadaed10356100e4e12b14e3c](https://user-images.githubusercontent.com/102637083/171084307-ff513f36-959d-48f7-bfe7-1b32f95e197d.png)

第一张图的菜单栏全是英文，但是第二张图的import { ExtendLocales } from './i18n'; 意思是导入中文包，为什么还是显示英文？

**Comment by wewoor** [comment]
@BojunZhong 这里需要在 `MoleculeProvider` 中设置 `defaultLocale` 参数：具体API解释请参考：

https://dtstack.github.io/molecule/zh-CN/docs/next/api/interfaces/IMoleculeProps#defaultlocale
